// <auto-generated />
using System;
using Ethos.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ethos.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903102922_TrainerBusinessRules")]
    partial class TrainerBusinessRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ethos.Api.Domain.Entities.AdminAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("admin_actions", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("MarkedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("ClassSessionId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("attendance_records", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.ClassEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("DanceClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StudentPackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("DanceClassId");

                    b.HasIndex("StudentPackageId");

                    b.HasIndex("StudentProfileId", "DanceClassId")
                        .IsUnique();

                    b.ToTable("class_enrollments", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.ClassSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("DanceClassId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("StudioRoom")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("DanceClassId");

                    b.ToTable("class_schedules", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.ClassSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("timestamptz");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ClassScheduleId");

                    b.HasIndex("ClassScheduleId", "SessionDate")
                        .IsUnique();

                    b.ToTable("class_sessions", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.DanceClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DanceStyle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("dance_classes", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.NotificationRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("notification_recipients", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.OtpVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Phone", "CreatedAt");

                    b.ToTable("otp_verifications", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ClassLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.PaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTransactionId");

                    b.ToTable("payment_events", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("INR");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<string>("RazorpayOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RazorpayPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RazorpaySignature")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RazorpayOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("payment_transactions", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "STUDENT",
                            Description = "Ethos student",
                            Name = "Student"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "TRAINER",
                            Description = "Ethos trainer",
                            Name = "Trainer"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "ADMIN",
                            Description = "Ethos administrator",
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.StudentPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ClassesAllowed")
                        .HasColumnType("integer");

                    b.Property<int>("ClassesUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("PaymentTransactionId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("student_packages", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("student_profiles", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("ApplicationNotes")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaymentVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TrainerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTransactionId")
                        .IsUnique()
                        .HasFilter("\"PaymentTransactionId\" IS NOT NULL");

                    b.HasIndex("TrainerProfileId");

                    b.ToTable("trainer_applications", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("TrainerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainerProfileId", "DayOfWeek", "StartTime", "EndTime")
                        .IsUnique();

                    b.ToTable("trainer_availability", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TrainerApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TrainerApplicationId");

                    b.ToTable("trainer_documents", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerPerformanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttendanceCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("AttendancePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("AverageFeedbackRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("FeedbackCount")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SessionsConducted")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TrainerProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("UniqueStudents")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopsConducted")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainerProfileId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("trainer_performance_snapshots", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerPermissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TrainerProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrainerProfileId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("TrainerProfileId1");

                    b.HasIndex("TrainerProfileId", "PermissionId")
                        .IsUnique();

                    b.ToTable("trainer_permission_overrides", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStudio")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("CurrentTierId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PrimaryDanceStyle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryDanceStyles")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TrainerCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("YouTubeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTierId");

                    b.HasIndex("TrainerCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("trainer_profiles", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ApplicationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("UpgradeFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.ToTable("trainer_tiers", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerTierHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewTierId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviousTierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TrainerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NewTierId");

                    b.HasIndex("PreviousTierId");

                    b.HasIndex("TrainerProfileId");

                    b.ToTable("trainer_tier_history", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerTierPermission", b =>
                {
                    b.Property<Guid>("TrainerTierId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("boolean");

                    b.HasKey("TrainerTierId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("trainer_tier_permissions", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerUpgradeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentTierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("RequestedTierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTierId");

                    b.HasIndex("RequestedTierId");

                    b.HasIndex("TrainerProfileId", "Status");

                    b.ToTable("trainer_upgrade_requests", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.Workshop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AdminApprovedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DanceStyle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("PriceApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PriceApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TrainerProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TrainerProposedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("WorkshopDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("TrainerProfileId");

                    b.ToTable("workshops", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.WorkshopBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkshopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("WorkshopId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("workshop_bookings", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.WorkshopFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ContentRating")
                        .HasColumnType("integer");

                    b.Property<int?>("EnergyRating")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("TeachingRating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("WorkshopId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WouldRecommend")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("WorkshopId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("workshop_feedback", (string)null);
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.ClassSession", "ClassSession")
                        .WithMany()
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSession");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.ClassEnrollment", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.DanceClass", "DanceClass")
                        .WithMany("Enrollments")
                        .HasForeignKey("DanceClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.StudentPackage", "StudentPackage")
                        .WithMany()
                        .HasForeignKey("StudentPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ethos.Api.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanceClass");

                    b.Navigation("StudentPackage");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.ClassSchedule", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.DanceClass", "DanceClass")
                        .WithMany("Schedules")
                        .HasForeignKey("DanceClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanceClass");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.ClassSession", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.ClassSchedule", "ClassSchedule")
                        .WithMany("Sessions")
                        .HasForeignKey("ClassScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSchedule");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.NotificationRecipient", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.Notification", "Notification")
                        .WithMany("Recipients")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.PaymentEvent", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany("Events")
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.StudentPackage", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.Package", "Package")
                        .WithMany("StudentPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("StudentPackages")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Ethos.Api.Domain.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerApplication", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany()
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ethos.Api.Domain.Entities.TrainerProfile", "TrainerProfile")
                        .WithMany("Applications")
                        .HasForeignKey("TrainerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentTransaction");

                    b.Navigation("TrainerProfile");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerAvailability", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.TrainerProfile", "TrainerProfile")
                        .WithMany("Availability")
                        .HasForeignKey("TrainerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainerProfile");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerDocument", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.TrainerApplication", "TrainerApplication")
                        .WithMany("Documents")
                        .HasForeignKey("TrainerApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainerApplication");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerPerformanceSnapshot", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.TrainerProfile", "TrainerProfile")
                        .WithMany("PerformanceSnapshots")
                        .HasForeignKey("TrainerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainerProfile");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerPermissionOverride", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.Permission", "Permission")
                        .WithMany("Overrides")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.TrainerProfile", "TrainerProfile")
                        .WithMany()
                        .HasForeignKey("TrainerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.TrainerProfile", null)
                        .WithMany("PermissionOverrides")
                        .HasForeignKey("TrainerProfileId1")
                        .HasConstraintName("FK_trainer_permission_overrides_trainer_profiles_TrainerProfi~1");

                    b.Navigation("Permission");

                    b.Navigation("TrainerProfile");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerProfile", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.TrainerTier", "CurrentTier")
                        .WithMany("Trainers")
                        .HasForeignKey("CurrentTierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ethos.Api.Domain.Entities.User", "User")
                        .WithOne("TrainerProfile")
                        .HasForeignKey("Ethos.Api.Domain.Entities.TrainerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentTier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerTierHistory", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.TrainerTier", "NewTier")
                        .WithMany()
                        .HasForeignKey("NewTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.TrainerTier", "PreviousTier")
                        .WithMany()
                        .HasForeignKey("PreviousTierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ethos.Api.Domain.Entities.TrainerProfile", "TrainerProfile")
                        .WithMany("TierHistory")
                        .HasForeignKey("TrainerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewTier");

                    b.Navigation("PreviousTier");

                    b.Navigation("TrainerProfile");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerTierPermission", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.Permission", "Permission")
                        .WithMany("TierPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.TrainerTier", "TrainerTier")
                        .WithMany("Permissions")
                        .HasForeignKey("TrainerTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("TrainerTier");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerUpgradeRequest", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.TrainerTier", "CurrentTier")
                        .WithMany()
                        .HasForeignKey("CurrentTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.TrainerTier", "RequestedTier")
                        .WithMany()
                        .HasForeignKey("RequestedTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.TrainerProfile", "TrainerProfile")
                        .WithMany("UpgradeRequests")
                        .HasForeignKey("TrainerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTier");

                    b.Navigation("RequestedTier");

                    b.Navigation("TrainerProfile");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.Workshop", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.TrainerProfile", "TrainerProfile")
                        .WithMany("Workshops")
                        .HasForeignKey("TrainerProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TrainerProfile");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.WorkshopBooking", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("WorkshopBookings")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.Workshop", "Workshop")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.WorkshopFeedback", b =>
                {
                    b.HasOne("Ethos.Api.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("WorkshopFeedbacks")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ethos.Api.Domain.Entities.Workshop", "Workshop")
                        .WithMany("Feedbacks")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.ClassSchedule", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.DanceClass", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.Notification", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.Package", b =>
                {
                    b.Navigation("StudentPackages");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.Permission", b =>
                {
                    b.Navigation("Overrides");

                    b.Navigation("TierPermissions");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.StudentProfile", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Enrollments");

                    b.Navigation("StudentPackages");

                    b.Navigation("WorkshopBookings");

                    b.Navigation("WorkshopFeedbacks");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerApplication", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerProfile", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Availability");

                    b.Navigation("PerformanceSnapshots");

                    b.Navigation("PermissionOverrides");

                    b.Navigation("TierHistory");

                    b.Navigation("UpgradeRequests");

                    b.Navigation("Workshops");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.TrainerTier", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("StudentProfile");

                    b.Navigation("TrainerProfile");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Ethos.Api.Domain.Entities.Workshop", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
